export const FETCH_JOBS = 'FETCH_JOBS';
export const FETCH_SINGLE_JOB = 'FETCH_SINGLE_JOB'; 
export const SET_JOBS = 'SET_JOBS';
export const ADD_JOB = 'ADD_JOB';
export const FAIL_MESSAGE = 'FAIL_MESSAGE';
export const SUCCESS_MESSAGE = 'SUCCESS_MESSAGE';
export const REMOVE_MESSAGE = 'REMOVE_MESSAGE';
export const INCOMPLETE_MESSAGE = 'INCOMPLETE_MESSAGE';